### ISSUE TITLE
Continue to develop this project

### ISSUE THREAD

**Issue by roy4801** [FjuOnlineJudge/cpcoj-backend#1]
Since the graduation project has ended for a period of time, shouldn't we regroup people which has free time to develop this project?

**Comment by allem40306** [comment]
Yes, I'll ask some people. And a problem is device, LiWen said he would offer us virtual machine (Vitualbox) and some IP. I'll check again.

**Comment by allem40306** [comment]
I focus on training wiki this semester so I maybe not join this.

**Comment by allem40306** [comment]
I create a [team](https://github.com/orgs/FjuOnlineJudge/teams/onlidejudge)

**Comment by roy4801** [comment]
Since we have discussed the project continuation, I will close this issue
